\i sql/01_create_rus_with_address.sql
\i sql/02_create_rus_with_phone.sql
\i sql/03_index_ip2loc_table.sql
\i sql/04_create_rus_with_geoip.sql
\i sql/05_union_russian_uids.sql
\i sql/06_index_russian_uids.sql
\i sql/07_check_addresses_with_uids.sql
\i sql/08_check_geoip_with_uids.sql
\i sql/09_form_cohorts_common.sql
\i sql/10a_form_rus_foreign_cohorts.sql
\i sql/10b_form_rus_foreign_cohorts.sql
\i sql/11_lifetime_in_days.sql
\i sql/12_months_between_function.sql
\i sql/13_compute_lifetime_cte.sql
\i sql/14_amount_of_russian_users_from_carts.sql
\i sql/15_russian_transactions_by_cohort_v1.sql
\i sql/16_russian_buyers_and_transactions_by_cohort_v2.sql
\i sql/17_create_view_ru_cohorts_transactions.sql
\i sql/18_q_max_conversion_month.sql
\i sql/19_q_max_total_cohort_conversion.sql
\i sql/20_create_view_foreign_cohorts_transactions.sql
\i sql/21_calendar_year.sql
\i sql/22_compute_openness_2017_2018.sql
\i sql/23_conversion_difference_2018-2017.sql
