Российские и зарубежные пользователи сервиса
=============================================

Как отличить отечественного пользователя от зарубежного?
-------------------------------------------------------------

Пользователь оставляет три кусочка информации, которые можно привязать к стране:

 - Адрес
 - Телефон
 - IP адрес

Беда в том, что мало у кого заполнены адреса, с телефонами ситуация несколько лучше,
и самая полная (хоть и не 100% полная) информация есть по IP адресам последнего входа.
Будем считать россиянами тех пользователей, у которых хотя бы один из этих признаков
указывает на Россию.

Конечная задача этого этапа -- построить список User ID-ов, которые считаются российскими.

=== Классификация адресов

~~~~~~~~~~~~~~~~~
CREATE TEMPORARY TABLE users_with_addresses as
    SELECT 
        u.id AS user_id, c.name AS city, r.name AS region, s.name AS country 
    FROM 
        case10.users AS u  
        JOIN case10.addresses AS a ON u.id         = a.addressable_id 
        JOIN case10.cities    AS c ON a.city_id    = c.id 
        JOIN case10.regions   AS r ON c.region_id  = r.id
        JOIN case10.countries AS s ON r.country_id = s.id
~~~~~~~~~~~~~~~~~

Проверяю, что табличка создалась:

~~~~~~~~~~~~~~
dgolub=> select * from users_with_addresses limit 2;
 user_id |   city    |               region               | country 
---------+-----------+------------------------------------+---------
  119414 | Lyantor   | Khanty-Mansiyskiy Avtonomnyy Okrug | Russia
  164276 | Serpukhov | MO                                 | Russia

dgolub=> select * from users_with_addresses where country <> 'Russia' limit 2;
 user_id |  city   |   region    | country 
---------+---------+-------------+---------
  170065 | Hadgāon | Maharashtra | India
  168259 | Narón   | Galicia     | Spain
~~~~~~~~~~~~~~

Ок, эта часть классификатора готова.

=== Классификация телефонов

Диапазоны для 

~~~~~~~~~~~~~
create temporary table users_with_phone as
    with russian_phones as (
        select id,phone
        from case10.users
        where 
            (phone::text ~ '^7[34589].........$')    -- all 10-digit numbers with prefix 73, 74, 75, 78, 79
            and (phone::text !~ '^78[45]0')    -- except Abkhazia and South Osetia (SO)
            and (phone::text !~ '^7940')       -- except Abkhazia
            and (phone::text !~ '^7995344')    -- except SO (ცხინვალი)
            and (phone::text !~ '^79971')      -- SO
            and (phone::text !~ '^799744')     -- SO
            and (phone::text !~ '^79976')      -- SO
    )
    select 
        u.id, u.phone,
        case 
            when ru.phone is not null then 'Russia'
            else 'Foreign'
        end country
    from 
        case10.users as u
        left join
        russian_phones as ru
        using (id)
    where
        u.phone is not null 
;
~~~~~~~~~~~~~

Проверяю:

~~~~~~~~~
dgolub=> select * from users_with_phone limit 3;
   id    |    phone    | country 
---------+-------------+---------
 1886022 | 79645822598 | Russia
 2019421 | 79625379259 | Russia
 1987320 | 79068740262 | Russia

dgolub=> select * from users_with_phone where country <> 'Russia' limit 3;
   id    |    phone     | country 
---------+--------------+---------
 2370045 | 375297000000 | Foreign
 2185526 | 375297000000 | Foreign
 2382362 |   9513245729 | Foreign
~~~~~~~~~

Вроде бы всё благополучно.

=== Определение страны последнего входа по IP адресу

Мне предстоит много запросов в большую таблицу диапазонов IP адресов,
поэтому хорошей идеей будет её индексирование по IP:

~~~~~~~~
CREATE INDEX ip2loc_from_idx ON case10.ip2location_db1 (ip_from);
CREATE INDEX ip2loc_to_idx   ON case10.ip2location_db1 (ip_to);
~~~~~~~~

Напоминаю, что я работаю с локальной базой и могу создавать в ней объекты без
особых проблем.

~~~~~~~~~~
create temporary table users_with_geoip as
with
    uid_ip as (
        select 
            id as uid, 
            last_sign_in_ip as ip_addr,
            last_sign_in_ip::inet - '0.0.0.0'::inet as int_addr
        from 
           case10.users
    )
select
   u.uid, u.ip_addr, u.int_addr,
   geoip.ip_from, geoip.ip_to, geoip.country_name 
from
   uid_ip as u
   join
   case10.ip2location_db1  as geoip
   on int_addr between ip_from and ip_to;
~~~~~~~~~~

Табличка создаётся долго (на моей базе, которая работает в контейнере и ограничена  по
ресурсам -- 7 минут).

Результат -- страны определены для 49914 пользователей из 50 тыс.

Проверяю, что получилось:

~~~~~~~~
dgolub=> select * from users_with_geoip limit 3;
   uid   |    ip_addr     |  int_addr  |  ip_from   |   ip_to    |    country_name    
---------+----------------+------------+------------+------------+--------------------
 1886022 | 89.169.72.78   | 1504266318 | 1504247808 | 1504313343 | Russian Federation
 2403464 | 37.98.248.114  |  627243122 |  627240960 |  627245055 | Russian Federation
  367821 | 128.73.199.169 | 2152318889 | 2151940096 | 2152464383 | Russian Federation

dgolub=> select * from users_with_geoip where country_name <> 'Russian Federation' limit 3;
   uid   |    ip_addr     |  int_addr  |  ip_from   |   ip_to    |    country_name    
---------+----------------+------------+------------+------------+--------------------
 2283296 | 116.36.201.154 | 1948567962 | 1948254208 | 1949302783 | Korea, Republic of
 2318834 | 178.168.180.74 | 2997400650 | 2997387264 | 2997420031 | Belarus
 2370045 | 46.56.231.58   |  775481146 |  775421952 |  775487487 | Belarus
~~~~~~~~

=== Создание общего списка российских UID-ов

Объединю для этого колонку UID всех трёх таблиц с адресами.

~~~~~~
create temporary table russian_users_ids as
   select user_id as uid from users_with_addresses where country = 'Russia'
   union
   select id as uid from users_with_phone where country = 'Russia'
   union
   select uid from users_with_geoip where country_name = 'Russian Federation'
   order by uid;
~~~~~~

В этот список придётся обращаться часто, поэтому проиндексирую его.

~~~~~~
dgolub=> create index russian_uids_idx on russian_users_ids (uid);
CREATE INDEX
~~~~~~

Проверяю, что эта таблица работает:

~~~~~~
dgolub=> select * from users_with_address where not exists (
    select uid from russian_users_ids where uid=user_id
);

 user_id |          city           |           region            |        country         
---------+-------------------------+-----------------------------+------------------------
  170065 | Hadgāon                 | Maharashtra                 | India
  168259 | Narón                   | Galicia                     | Spain
  108773 | Riyadh                  | Ar Riyāḑ                    | Saudi Arabia
....
 2474656 | Petatlán                | Guerrero                    | Mexico
 2492617 | Kivertsi                | Volyn                       | Ukraine
 2492871 | Chuhuyiv                | Kharkiv                     | Ukraine
(121 rows)
~~~~~~

Аналогично проверяю с таблицей GeoIP:

~~~~~~
select * from users_with_geoip where not exists (
    select uid from russian_users_ids 
    where users_with_geoip.uid=russian_users_ids.uid
);
~~~~~~

Итак, создан список пользователей из России. Обратный список (иностранцев) нет смысла
делать, одного списка тут достаточно.  Поиск идёт достаточно быстро (B-Tree).


Когортный анализ российских пользователей
------------------------------------------

> Постройте когортный анализ по пользователям из России.
> В каком месяце была максимальная конверсия в оплату из зарегистрировавшихся в
> том же месяце? Учитывайте только месяцы, где было 100 и больше регистраций.

Собираем когорты по месяцам, учитываем только российских пользователей и за основу берём
поле `created_at` из таблицы `case10.users`.

select
    count(id), date_trunc('month', created_at) as cohort
from case10.users
group by cohort
order by cohort;
